---
# https://kifarunix.com/configure-highly-available-haproxy-with-keepalived-on-ubuntu-20-04/

- name: Install keepalived
  become: true
  shell: apt install keepalived --yes

- name: Configure IP forwarding
  become: true
  shell: sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf

- name: Configure non-local binding
  become: true
  shell: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf

- name: Configure non-local binding
  become: true
  shell: sysctl -p

- name: Create keepalived.conf
  become: true
  file:
    path: /etc/keepalived/keepalived.conf
    state: touch